version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
      - external

  drupal:
    image: drupal:8.7.8-fpm-alpine
    container_name: drupal
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - drupal-data:/var/www/html
      - ./drupal-data/sites:/var/www/html/sites
      - ./drupal-data/modules:/var/www/html/modules
      - ./drupal-data/themes:/var/www/html/themes

  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - drupal-data:/var/www/html
      - ./drupal-data/sites:/var/www/html/sites
      - ./drupal-data/modules:/var/www/html/modules
      - ./drupal-data/themes:/var/www/html/themes
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - internal
      - external

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  drupal-data:
